[package]
name = "era-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anstream = "1"
anstyle = "1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { version = "4", features = ["derive"] }
era-core = { path = "../core" }
era-materialization = { path = "../materialization" }
era-repository = { path = "../repository" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[dev-dependencies]
assert_cmd = "2"
tempfile = "3"

[[bin]]
name = "era"
path = "src/main.rs"
