[package]
name = "era-object-store"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-trait = "0.1"
era-core = { path = "../core" }
tokio = { version = "1", features = ["fs", "io-util", "macros", "rt"] }

[dev-dependencies]
tempfile = "3"
